const [SWITCH, SIGNIN, SIGNUP, SIGNIN_ASYNC, SIGNUP_ASYNC, SIGNOUT] = 
      ["SWITCH", "SIGNIN", "SIGNUP","SIGNIN_ASYNC", "SIGNUP_ASYNC", "SIGNOUT"];

export { SWITCH, SIGNIN, SIGNUP, SIGNIN_ASYNC, SIGNUP_ASYNC, SIGNOUT };