const [SWITCH, SIGNIN, SIGNUP, SIGNIN_ASYNC, SIGNUP_ASYNC, SIGNOUT, DISABLEFORM ] = 
      ["SWITCH", "SIGNIN", "SIGNUP","SIGNIN_ASYNC", "SIGNUP_ASYNC", "SIGNOUT", "DISABLEFORM"];

export { SWITCH, SIGNIN, SIGNUP, SIGNIN_ASYNC, SIGNUP_ASYNC, SIGNOUT, DISABLEFORM };